[2024-06-12T12:06:24.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T12:06:24.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.spotify_etl_final manual__2024-06-12T12:04:32.357504+00:00 [queued]>
[2024-06-12T12:06:24.249+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.spotify_etl_final manual__2024-06-12T12:04:32.357504+00:00 [queued]>
[2024-06-12T12:06:24.250+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-12T12:06:24.279+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spotify_etl_final> on 2024-06-12 12:04:32.357504+00:00
[2024-06-12T12:06:24.298+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=94) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T12:06:24.305+0000] {standard_task_runner.py:63} INFO - Started process 96 to run task
[2024-06-12T12:06:24.304+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'spotify_etl_final', 'manual__2024-06-12T12:04:32.357504+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmpopi677eh']
[2024-06-12T12:06:24.306+0000] {standard_task_runner.py:91} INFO - Job 262: Subtask spotify_etl_final
[2024-06-12T12:06:24.404+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.spotify_etl_final manual__2024-06-12T12:04:32.357504+00:00 [running]> on host d317f063dba7
[2024-06-12T12:06:24.661+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='spotify_etl_final' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T12:04:32.357504+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T12:04:32.357504+00:00'
[2024-06-12T12:06:24.664+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T12:06:24.665+0000] {logging_mixin.py:188} INFO - ETL process started
[2024-06-12T12:06:25.101+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T12:06:25.102+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_final_dag.py", line 130, in ETL
    df = spotify_etl()
         ^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_etl.py", line 83, in spotify_etl
    load_df = return_dataframe()
              ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spotify_etl.py", line 46, in return_dataframe
    for song in data["items"]:
                ~~~~^^^^^^^^^
KeyError: 'items'
[2024-06-12T12:06:25.120+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=spotify_etl_final, run_id=manual__2024-06-12T12:04:32.357504+00:00, execution_date=20240612T120432, start_date=20240612T120624, end_date=20240612T120625
[2024-06-12T12:06:25.155+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 262 for task spotify_etl_final ('items'; 96)
[2024-06-12T12:06:25.175+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T12:06:25.227+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T12:06:25.239+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
