[2024-06-11T16:18:57.678+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: spotify_final_dag.create_table manual__2024-06-11T16:08:28.073929+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
