[2024-06-12T07:18:31.866+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T07:18:31.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.create_table scheduled__2024-06-11T20:20:00+00:00 [queued]>
[2024-06-12T07:18:31.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.create_table scheduled__2024-06-11T20:20:00+00:00 [queued]>
[2024-06-12T07:18:31.940+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-12T07:18:31.959+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-06-11 20:20:00+00:00
[2024-06-12T07:18:31.991+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=681) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T07:18:31.994+0000] {standard_task_runner.py:63} INFO - Started process 685 to run task
[2024-06-12T07:18:32.005+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'create_table', 'scheduled__2024-06-11T20:20:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmpvvcet8uw']
[2024-06-12T07:18:32.007+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask create_table
[2024-06-12T07:18:32.102+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.create_table scheduled__2024-06-11T20:20:00+00:00 [running]> on host d317f063dba7
[2024-06-12T07:18:32.254+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-11T20:20:00+00:00'
[2024-06-12T07:18:32.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T07:18:32.258+0000] {sql.py:276} INFO - Executing: 
	CREATE TABLE IF NOT EXISTS my_played_tracks(
	song_name VARCHAR(200),
	artist_name VARCHAR(200),
	played_at VARCHAR(200),
	timestamp VARCHAR(200),
	CONSTRAINT primary_key_constraint PRIMARY KEY (played_at)
	)
        
[2024-06-12T07:18:32.289+0000] {base.py:84} INFO - Using connection ID 'postgre_sql' for task execution.
[2024-06-12T07:18:32.341+0000] {base.py:84} INFO - Using connection ID 'postgre_sql' for task execution.
[2024-06-12T07:18:32.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T07:18:32.343+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-06-12T07:18:32.400+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=create_table, run_id=scheduled__2024-06-11T20:20:00+00:00, execution_date=20240611T202000, start_date=20240612T071831, end_date=20240612T071832
[2024-06-12T07:18:32.428+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 154 for task create_table (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 685)
[2024-06-12T07:18:32.492+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T07:18:32.529+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-12T07:18:32.545+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T07:18:32.548+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
